apiVersion: apps/v1
kind: Deployment
metadata:
  name: head-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: head-model
  template:
    metadata:
      labels:
        app: head-model
    spec:
      containers:
      - name: head-model-container
        image: lotring/head-model:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: head-service
spec:
  selector:
    app: head-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tail-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tail-model
  template:
    metadata:
      labels:
        app: tail-model
    spec:
      containers:
      - name: tail-model-container
        image: lotring/tail-model:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: tail-service
spec:
  selector:
    app: tail-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      serviceAccountName: ui-serviceaccount
      containers:
      - name: ui
        image: lotring/ui:split
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: default
spec:
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31000
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ui-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: ui-role
rules:
- apiGroups: ["operator.wnguddn777.com"]
  resources: ["monitorings"]
  verbs: ["create", "update", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ui-serviceaccount
  namespace: default
roleRef:
  kind: Role
  name: ui-role
  apiGroup: rbac.authorization.k8s.io

